apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 80 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 80 }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: {{ .Values.namespace }}
spec:
  stripPrefix:
    forceSlash: true
    prefixes:
      - {{ .Values.ingress.path }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name | default "lumina-ingress" }}
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespace }}-strip-prefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port | default 80 }}
{{- if .Values.rootStaticIngress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.rootStaticIngress.name | default "lumina-root-static" }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - http:
        paths:
          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port | default 80 }}
          - path: /favicon.svg
            pathType: Exact
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port | default 80 }}
          - path: /icons.svg
            pathType: Exact
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port | default 80 }}
          - path: /vite.svg
            pathType: Exact
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port | default 80 }}
{{- end }}
